ALTER TABLE our_adventures.activities
  ADD COLUMN IF NOT EXISTS link TEXT;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'our_adventures'
      AND table_name = 'users'
      AND column_name = 'id'
      AND data_type = 'text'
  ) THEN
    ALTER TABLE our_adventures.completions
      DROP CONSTRAINT IF EXISTS completions_user_id_fkey;

    ALTER TABLE our_adventures.users
      RENAME COLUMN id TO google_sub;

    ALTER TABLE our_adventures.users
      ALTER COLUMN google_sub DROP NOT NULL;

    ALTER TABLE our_adventures.users
      ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

    ALTER TABLE our_adventures.users
      DROP CONSTRAINT IF EXISTS users_pkey;

    ALTER TABLE our_adventures.users
      ADD PRIMARY KEY (id);

    ALTER TABLE our_adventures.users
      ADD CONSTRAINT users_google_sub_key UNIQUE (google_sub);

    ALTER TABLE our_adventures.completions
      DROP CONSTRAINT IF EXISTS completions_pkey;

    ALTER TABLE our_adventures.completions
      ADD COLUMN user_id_v2 BIGINT;

    UPDATE our_adventures.completions completions
    SET user_id_v2 = users.id
    FROM our_adventures.users users
    WHERE completions.user_id = users.google_sub;

    ALTER TABLE our_adventures.completions
      DROP COLUMN user_id;

    ALTER TABLE our_adventures.completions
      RENAME COLUMN user_id_v2 TO user_id;

    ALTER TABLE our_adventures.completions
      ALTER COLUMN user_id SET NOT NULL;

    ALTER TABLE our_adventures.completions
      ADD CONSTRAINT completions_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES our_adventures.users(id);

    ALTER TABLE our_adventures.completions
      ADD PRIMARY KEY (activity_id, user_id);
  END IF;
END
$$;

ALTER TABLE our_adventures.users
  ADD COLUMN IF NOT EXISTS google_sub TEXT;

ALTER TABLE our_adventures.users
  ALTER COLUMN google_sub DROP NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'users_google_sub_key'
      AND connamespace = 'our_adventures'::regnamespace
  ) THEN
    ALTER TABLE our_adventures.users
      ADD CONSTRAINT users_google_sub_key UNIQUE (google_sub);
  END IF;
END
$$;
